language: python
sudo: false
services:
  - cassandra
  - redis-server

python:
  - "3.6"
  - "pypy"

install:
- pip install -U pip
- pip install -e .[cassandra,sqlalchemy,crypto]
- pip install -r dev_requirements.txt
- pip install python-coveralls

env:
  global:
    - CASSANDRA_PROTOCOL_VERSION=2
    - CASSANDRA_HOSTS=127.0.0.1

script:
- if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run -m unittest discover eventsourcing.tests -v ; fi
- if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then python -m unittest discover eventsourcing.tests -v ; fi

after_success:
- if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls ; fi
