language: python
sudo: false
services:
  - postgresql

python:
  - "3.6"

install:
- pip install -U pip
- pip install six
- pip install python-dateutil
- pip install peewee
- pip install peewee_async
- pip install aiounittest
- pip install aiopg
- pip install -r dev_requirements.txt
- pip install python-coveralls

env:
  global:
    - PGDB=postgres
    - PGUSER=postgres
    - PGPASS=

script:
- if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run -m unittest tests -v ; fi
- if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then python -m unittest discover tests -v ; fi

after_success:
- if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls ; fi
