language: python
sudo: false
services:
  - cassandra
  - redis-server

python:
  - "3.6"
  - "pypy"

install:
- pip install -U pip
- pip install six
- pip install python-dateutil
- pip install peewee
- pip install peewee_async
- pip install aiounittest
- pip install aiopg
- pip install -r dev_requirements.txt
- pip install python-coveralls

script:
- if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run -m unittest discover tests -v ;
- if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then python -m unittest tests;

after_success:
- if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls ;
